unilink/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('unilink_app.urls', namespace="unilink_app")),
    path('admin/', admin.site.urls),
]

unilink_app/urls.py
from django.urls import path
from . import views

app_name = "unilink_app"

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('c/<str:collection_link>', views.CollectionView.as_view(), name='collectionView'),
    path('edit_name/<str:collection_link>', views.EditCollectionName.as_view(), name='editname'),
    path('set_pass/<str:collection_link>', views.SetCollectionPassword.as_view(), name='setcollpass'),
    path('how_to_use', views.HowToUse.as_view(), name='howtouse'),
    path('aboutus', views.AboutUs.as_view(), name='aboutus'),
    path('switch_visibility/<str:collection_link>', views.SwitchVisibilty.as_view(), name='visi'),
]

unilink_app/models.py
from django.db import models
from .utils import create_shortened_url
from .link_process import extract_info
from django.utils import timezone
from django.contrib.auth.hashers import make_password
date_generated = models.DateTimeField(default=timezone.now)


class UniCollection(models.Model):
    '''
    Creates a collection base on which all others links will be added
    ''' 
    created = models.DateTimeField(auto_now_add=True)
    collection_name = models.CharField(max_length=300, blank=True, null = True)
    description = models.CharField(max_length = 600, null= True, blank = True)
    short_url = models.CharField(max_length=15, unique=True)
    password = models.CharField(max_length=600, null=True, blank=True)
    public = models.CharField(max_length=15, default=0)

    class Meta:
        db_table = "unicollection"
        ordering = ["-created"]

    def __str__(self):
        return self.short_url

    def save(self, *args, **kwargs):
        if not self.short_url:
            self.short_url = create_shortened_url(self)
        if self.password != None:
            self.password = make_password(self.password)
        super().save(*args, **kwargs)


class Link(models.Model):
    """
    Model for links to be added
    """

    created = models.DateTimeField(auto_now_add=True)
    collection = models.ForeignKey(UniCollection, on_delete=models.CASCADE, null = True)
    title = models.CharField(max_length = 500, null = True, blank=True)
    image_url = models.URLField(blank=True, null =True)
    favicon_url = models.URLField(null = True, blank = True)
    description = models.CharField(max_length = 1000, null = True, blank=True)
    host_name = models.CharField(max_length = 500, null = True, )
    url = models.URLField()
    
    class Meta:
        db_table = "links"
        ordering = ["-created"]
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        title,image_url, desc, favicon, host_name = extract_info(self.url)
        self.title = title
        self.image_url = image_url
        self.description = desc
        self.favicon_url = favicon
        self.host_name = host_name
        super().save(*args, **kwargs)

unilink_app/forms.py
from django import forms
from .models import UniCollection, Link

class UniCollectionForm(forms.ModelForm):
    collection_url = forms.URLField(widget=forms.URLInput(
        attrs={"class": "link-input", "placeholder": "Paste here a link..."}))
    
    class Meta:
        model = UniCollection
        fields = ('collection_url',)


class CollectionPasswordAdd(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={"class": "link-input", "placeholder": "Password..."}))
    
    class Meta:
        model = UniCollection
        fields = ("password",)


class UniCollectionEditForm(forms.ModelForm):
    collection_name = forms.CharField(widget=forms.TextInput(
        attrs={"class": "sim-input", "placeholder": "Name this unilection..."}))
    
    description = forms.CharField(widget=forms.TextInput(
        attrs={"class": "sim-input", "placeholder": "Description here..."}), required=False)

    class Meta:
        model = UniCollection
        fields = ('collection_name', 'description')


class CollectionAddForm(forms.ModelForm):
    url = forms.URLField(widget=forms.URLInput(
        attrs={"class": "link-input", "placeholder": "Your link to save"}))
    
    class Meta:
        model = Link
        fields = ("url",)

unilink_app/views.py
from django.db.models import Q
from django.shortcuts import render , redirect, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from .models import UniCollection, Link
from .forms import UniCollectionForm, CollectionAddForm, UniCollectionEditForm, CollectionPasswordAdd
from django.views import View
from django.contrib.auth.hashers import check_password
from django.contrib import messages
import json


class Home(View):
    template = 'home.html'

    def get(self, request):
        sort = request.GET.get('sort')

        context = {}
        context['form'] = UniCollectionForm()
        context["page_name"] = "home"
        
        collection = UniCollection.objects.filter(public = 0)
        if sort == "oldest":
            collection = UniCollection.objects.filter(public = 0).order_by('created')

        context["links"] = collection
        return render(request, self.template, context)
    
    def post(self, request):
        context = {}
        context['form'] = UniCollectionForm()
        collection_form = UniCollectionForm(request.POST)
        if collection_form.is_valid():
            shortened_object = collection_form.save()
            new_url = request.build_absolute_uri('/c/') + shortened_object.short_url
            link = collection_form.cleaned_data['collection_url']
            msg = "Your new collection is succesfully created. Go ahead & click on the lock icon in the top right menu and create a password so, that you can add new links."
            messages.success(request, msg)
            return redirect(new_url + "?u=" + link)

        context['errors'] = collection_form.errors
        return render(request, self.template, context)


class CollectionView(View):
    template = 'collection.html'

    def get(self, request, collection_link):
        context = {}
        sort = request.GET.get('sort')

        inst = get_object_or_404(UniCollection, short_url = collection_link)

        # if UniCollection.objects.get(short_url = collection_link).password == "":
        context["pp_form"] = CollectionPasswordAdd()

        context['form'] = CollectionAddForm()
        context["coll_form"] = UniCollectionEditForm(instance = inst)
        context["form"].fields["url"].initial = request.GET.get("u")
        context["visibility"] = UniCollection.objects.get(short_url = collection_link).public

        if 'q' in request.GET:
            item = request.GET.get('q')

            links = UniCollection.objects.get(short_url = collection_link).link_set.filter(Q(title__icontains=item) | Q(host_name__icontains=item))
            if sort == "oldest":
                links = UniCollection.objects.get(short_url = collection_link).link_set.filter(Q(title__icontains=item) | Q(host_name__icontains=item)).order_by('created')
            
            context["links"] = links
            context["count"] = links.count()
            context["link_id"] = collection_link
            context["page_name"] = "collection"
            context["description"] = UniCollection.objects.get(short_url = collection_link).description
            context["search_text"] = request.GET.get("q")
            return render(request, self.template, context)


        links = UniCollection.objects.get(short_url = collection_link).link_set.all()
        if sort == "oldest":
            links = UniCollection.objects.get(short_url = collection_link).link_set.all().order_by('created')

        context["links"] = links
        context["count"] = links.count()
        context["link_id"] = collection_link
        context["page_name"] = "collection"
        context["description"] = UniCollection.objects.get(short_url = collection_link).description
        return render(request, self.template, context)

    def post(self, request, collection_link):
        context = {}
        context['form'] = CollectionAddForm()
        form = CollectionAddForm(request.POST)
        if form.is_valid():
            uni = get_object_or_404(UniCollection, short_url= collection_link)
            form.instance.collection = uni
            form_object = form.save()
            return redirect("/c/" + collection_link)

        return HttpResponse(form.errors)

# View for adding collection details.
class EditCollectionName(View):
    def post(self, request, collection_link):
        instance = get_object_or_404(UniCollection, short_url = collection_link)
        coll_form = UniCollectionEditForm(request.POST or None, instance=instance)
        if coll_form.is_valid():
            coll_form.save()
            return redirect("/c/" + collection_link)
        return HttpResponse(coll_form.errors)

# View for setting up the collection password.
class SetCollectionPassword(View):
    def post(self, request, collection_link):
        instance = get_object_or_404(UniCollection, short_url = collection_link)
        pp_form = CollectionPasswordAdd(request.POST or None, instance = instance)
        if pp_form.is_valid():
            x = pp_form.cleaned_data.get('password')

            encrypted = UniCollection.objects.get(short_url = collection_link).password
            if not encrypted == None:
                if check_password(x, encrypted):
                    msg = "Congrats! You unlocked this collection try adding new links."
                    messages.success(request, msg)
                    return redirect("/c/" + collection_link)
                else:
                    msg = "Your password for this collection is incorrect, please try again!"
                    messages.warning(request, msg)
                    return redirect("/c/" + collection_link)

            msg = "Password is successfully created!"
            messages.success(request, msg)
            pp_form.save()
            return redirect("/c/" + collection_link)
        return HttpResponse(pp_form.errors)


class HowToUse(View):
    def get(self, request):
        template = "howtouse.html"
        return render(request, template)


class AboutUs(View):
    def get(self, request):
        template = "aboutus.html"
        return render(request, template)

# View for making the collection public or private
class SwitchVisibilty(View):
    def post(self, request, collection_link):
        if request.method=='POST':
            obj = UniCollection.objects.get(short_url = collection_link)
            raw = json.loads(request.body)
            if raw['data'] == 0 or raw['data'] == 1:
                obj.public = raw['data']
                obj.save()
                return JsonResponse({'status':'Success', 'msg': 'save successfully'})
        else:
            return JsonResponse({'status':'Fail', 'msg':'Not a valid request'})

unilink_app/templates/aboutus.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<div class="about_container">
    <div class="a_inner">
        <div>
            <div class="a_heading">UniLink</div>
            <p class="subtitle">Your new friendly link manager!</p>
            <p>Unilink makes it easy to organise and share your links with others.</p>
            <p>With unilink you may make a links collection and share it with others.</p>
            <p>People may also edit add their links too.</p>
        </div>

        <div>
            <img class="lazy imgab swing" data-src="{% static 'img/jgj.PNG' %}" alt="">
        </div>
    </div>
</div>
{% endblock content %}

unilink_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>UNILink - The ultimate link manager!</title>
      <!-- Primary Meta Tags -->
      <meta name="title" content="UNILink - The ultimate link manager!">
      <meta name="description" content="UNILink is a friendly link manager. Through this tool you can make public or private links collection, and also explore awesome links collections curated by other people.">
      <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
      <!-- Open Graph / Facebook -->
      <meta property="og:type" content="website">
      <meta property="og:url" content="{% static 'img/jgj.PNG' %}">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta property="og:title" content="UNILink - The ultimate link manager!">
      <meta property="og:description" content="UNILink is a friendly link manager. Through this tool you can make public or private links collection, and also explore awesome links collections curated by other people.">
      <meta property="og:image" content="{% static 'img/jgj.PNG' %}">
      <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
      <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
   </head>
   <body>
      <!--  Toast notification starts  -->
      <div id="toast">
         <div id="img">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
               <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
               <circle cx="12" cy="12" r="9" />
               <line x1="12" y1="8" x2="12.01" y2="8" />
               <polyline points="11 12 12 12 12 16 13 16" />
            </svg>
         </div>
         <div id="desc"></div>
      </div>
      <div class="pop-container" id="popup">
         <div class="pop-inner">
            <div class="p-item">
               <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-info-circle" width="18" height="18" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <circle cx="12" cy="12" r="9" />
                  <line x1="12" y1="8" x2="12.01" y2="8" />
                  <polyline points="11 12 12 12 12 16 13 16" />
               </svg>
               <span>
                  <b>Description:</b> 
                  <svg xmlns="http://www.w3.org/2000/svg" id="pop-x" width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                     <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                     <circle cx="12" cy="12" r="9" />
                     <path d="M10 10l4 4m0 -4l-4 4" />
                  </svg>
               </span>
            </div>
            <div class="p-item">
               <span id="tabtn"></span>
            </div>
            <div id="third__" class="p-item">
               <svg xmlns="http://www.w3.org/2000/svg"  width="18" height="18" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5" />
                  <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5" />
               </svg>
               <span id="card_link">Copy Url link</span>
            </div>
            {% block passwordBlock %}{% endblock passwordBlock %}
         </div>
      </div>
      <header>
         <a class="logo" href="{% url 'unilink_app:home' %}">
            <svg xmlns="http://www.w3.org/2000/svg"  width="35" height="35" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
               <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
               <path d="M21 14l-9 7l-9 -7l3 -11l3 7h6l3 -7z" />
            </svg>
            <span>UniLink</span>
         </a>
         <input id="nav" type="checkbox">
         <label for="nav"></label>
         <nav>
            <ul>
               {% if page_name == 'collection' %}
               {% block visib %}{% endblock visib %}
               <li>
                  <span>
                     <svg id="tip-lock" onclick="setup_pp()" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <rect x="5" y="11" width="14" height="10" rx="2" />
                        <circle cx="12" cy="16" r="1" />
                        <path d="M8 11v-4a4 4 0 0 1 8 0v4" />
                     </svg>
                  </span>
               </li>
               <li>
                  <span>
                     <svg id="tip-copyn" onclick="copylink()" xmlns="http://www.w3.org/2000/svg"  width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M10 14a3.5 3.5 0 0 0 5 0l4 -4a3.5 3.5 0 0 0 -5 -5l-.5 .5" />
                        <path d="M14 10a3.5 3.5 0 0 0 -5 0l-4 4a3.5 3.5 0 0 0 5 5l.5 -.5" />
                     </svg>
                  </span>
               </li>
               <li>
                  <span>
                     <svg id="tip-desc" description="{{ description }}" onclick="setup_popup_dsc(this)" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <line x1="12" y1="8" x2="12.01" y2="8" />
                        <rect x="4" y="4" width="16" height="16" rx="2" />
                        <polyline points="11 12 12 12 12 16 13 16" />
                     </svg>
                  </span>
               </li>
               <li>
                  <span>
                     <svg id="tip-add" onclick="window.location.href='/'" xmlns="http://www.w3.org/2000/svg"  width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <circle cx="12" cy="12" r="9" />
                        <line x1="9" y1="12" x2="15" y2="12" />
                        <line x1="12" y1="9" x2="12" y2="15" />
                     </svg>
                  </span>
               </li>
               {% endif %}
               <li>
                  <span>
                  <svg id="tip-share" onclick="share()" xmlns="http://www.w3.org/2000/svg"  width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                     <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                     <circle cx="6" cy="12" r="3" />
                     <circle cx="18" cy="6" r="3" />
                     <circle cx="18" cy="18" r="3" />
                     <line x1="8.7" y1="10.7" x2="15.3" y2="7.3" />
                     <line x1="8.7" y1="13.3" x2="15.3" y2="16.7" />
                  </svg>
                  </a>
               </li>
            </ul>
         </nav>
      </header>
      {% block content %}{% endblock content %}
      <div class="footer">
         <div class="footer-con">
            <div class="s-links">
               <span style="color: #fff;">© 2021 UNILink</span>
               <a href="{% url 'unilink_app:aboutus' %}">About us</a>
               <a href="{% url 'unilink_app:howtouse' %}">How it works?</a>
            </div>
            <div class="social">
               <svg onclick="window.location.href= 'https://github.com/abhiprojectz/unilink'" xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5" />
               </svg>
            </div>
         </div>
      </div>
      <script>
         window.onload = () => {
            var url = new URL(location.href)
            if (url.searchParams.get("sort") == "oldest") {
               document.querySelector("#sort").value = "oldest";
            }
         }
         
         var arr = ["#D65DB1",
               "#FF6F91",
               "#FF9671",
               "#FFC75F",
               "#F9F871",
               "#0089BA",
               "#FBEAFF",
               "#C4FCEF",
               "#FF8066",
               "#FEFEDF",
               "#D0E9F4",
               "#008CCC",
               "#4FFBDF",
               "#C493FF",
               "#FACCFF",
               ];
         
         var all_el = document.querySelectorAll(".boxc");
         
         all_el.forEach((el) => {
           el.style.backgroundColor = arr[Math.floor(Math.random() * arr.length)];
         })
      </script>
      <script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.4.0/dist/lazyload.min.js"></script>
      <!-- === Tooltip . Tippy scripts === -->
      <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.min.js"></script>
      <script src="https://unpkg.com/tippy.js@6/dist/tippy-bundle.umd.js"></script>
      <script src="{% static 'js/script.min.js' %}"></script>
      <script>
         var ll = new LazyLoad({
         });
      </script>
   </body>
</html>

unilink_app/templates/home.html
{% extends 'base.html' %} 
{% block content %}
<div class="app-container">
   <div class="slitin app-wrapper">
      <h1>Forgot Managing your links anymore!</h1>
      <p>UNILink - makes Links manageable.</p>
      <div class="links-container rollin">
         <form action="" method="POST">
            <div class="inp-wrap">
               {% csrf_token %}
               {{form.collection_url}}
               <button class="sub">
                  <svg style="margin-left: 10px;" xmlns="http://www.w3.org/2000/svg" class="sicon" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="#651FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
                     <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                     <rect x="4" y="4" width="16" height="16" rx="2" />
                     <line x1="9" y1="12" x2="15" y2="12" />
                     <line x1="12" y1="9" x2="12" y2="15" />
                  </svg>
               </button>
            </div>
         </form>
         {% if errors %}
         <div class="alert alert-danger mt-4" role="alert">
            <p>{{errors}}</p>
         </div>
         {% endif %}
      </div>
      <p class="grey-t">You need one link to create a manageble link.</p>
   </div>
</div>
<div class="links-gallery-container">
   <div class="links-g">
      <div class="l-head">
         <h2>Popular Unilections</h2>
         <div class="tags-list-main">
            <div>
               <span class="tag">#all</span>
            </div>
            <section class="dropsel">
               <span class="iosr">Sort By: </span>
               <select id="sort" class="selectbor" onchange="update_sort(this.value)">
                  <option value="newest">Newest</option>
                  <option value="oldest">Oldest</option>
               </select>
            </section>
         </div>
      </div>
      <div class="grid-container">
         <div class="grid">
            {% for i in links %}
            <div class="boxc" onclick="window.location.href='c/{{ i.short_url }}'">
               <div class="page-wrapper">
                 <div class="wrapper-title">
                   <span class="fr-title">{{ i.collection_name }}</span>
                </div>
                 <div class="wrapper-counts">
                   <div class="icon-text">
                      <div class="iconz">
                         <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#333" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <circle cx="12" cy="12" r="9"></circle>
                            <polyline points="12 7 12 12 15 15"></polyline>
                         </svg>
                      </div>
                      <span class="text front">{{ i.created }}</span>
                   </div>
                </div>
               </div>
             </div>
            {% endfor %}
         </div>
      </div>
      <button class="explore">
         Explore 
         <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-right" width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#651FFF" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <polyline points="9 6 15 12 9 18" />
         </svg>
      </button>
   </div>
</div>
{% endblock content %}

unilink_app/templates/howtouse.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<div class="main-container">
   <div class="inner-content">
      <div class="box-header">
         <p>STEPS</p>
         <div class="tagline">
            How it <span class="purple">Works?</span>
         </div>
      </div>
      <div class="middle-container flex">
         <div class="box">
            <h2>1. Create a collection</h2>
            <p>Visit the main paste the link and click on + button. </p>
         </div>
         <div class="box">
            <h2>2. Add a password to your collection if you don't want others to add links in it.</h2>
            <p>Paste as many links as you want.</p>
         </div>
         <div class="box">
            <h2>3. Blazing fast automation!</h2>
            <p>All the links title, images, descriptions gets added automatically by the tool, so you don't need to add them manually.</p>
         </div>
         <div class="box">
            <h2>4. Share it with your friends.</h2>
            <p>You may also share your password with them to let them add their contibutions too.</p>
         </div>
         <div class="box">
            <h2>5. Easy search</h2>
            <p>Search your links in a collection seemingly.</p>
         </div>
         <div class="box">
            <h2>6. Express what's the collection is for!</h2>
            <p>You may add title, description to a collection.</p>
         </div>
         <div class="box">
            <h2>7. Password can be created only once for a collection.</h2>
            <p>Don't forget it keep it with you at safe place.</p>
         </div>
         <div class="box">
            <h2>8. Simplest for even school kids!</h2>
            <p>Any school kids can use this tool to maange their links with ease can be it assignments, docs, homework or maybe any youtube tutorial.</p>
         </div>
         <div class="box">
            <h2>9. Fully opensourced</h2>
            <p>Everything is opensourced checkout the github its first tool, that is opensourced in this genre.</p>
         </div>
         <div class="box">
            <h2>10. Privacy free & customizable</h2>
            <p>You can set your collection as private so that it will be with you only! <br> and will never appear on the main site collections. <br> You may always tune up this thing that is the owner of the collection.</p>
         </div>
      </div>
   </div>
</div>
{% endblock content %}